### ISSUE TITLE
schedule and deleting/refreshing

### ISSUE THREAD

**Issue by Jrizzi1** [jprante/elasticsearch-jdbc#213]
I have a river set up against an Oracle sql statement, and the schedule parameter running correctly (currently fetching every 5 mins)

My question is , I delete a row from the database table being rivered, I was hoping that the river would remove that item from the index as well, however it remains

Most of the knowledge base i've searched on the web has mentioned setting the versioning or digesting parameters for housekeeping (?) , but from what i can see, these parameters have been deprecated. Most also mention using "poll" rather than schedule , i did find however that schedule has replaced poll as a parameter.

How is it best to handle this situation? is it simply the recreating of the index and river by an outside job script, or can this be done within the plugin?

**Comment by digitaldavenyc** [comment]
Are there any plans to re-introduce support for deleted row detection? I may switch the entire database to mongodb since the river for mongo does support deleted records, if we have to develop around this, I feel like the river looses a lot of value.

**Comment by jprante** [comment]
MongoDB river uses oplog stream parsing. JDBC plugin uses plain SQL, without knowing the underlying database at all. So the comparison is not really fair. I share the importance of the problem, though.

If you use MySQL, there is the possibility to extend the plugin by binlog event stream listening https://github.com/shyiko/mysql-binlog-connector-java to the next version, because it is open source. I have to evaluate this more in detail, it could be implemented as an extra plugin to the plugin.

**Comment by digitaldavenyc** [comment]
The approach of using straight SQL makes the JBDC river transportable to different databases but also is not the most optimal way. I know MongoDB use the oplog but because it uses this approach, it's performance is far better.

The idea of using a binlog connector sounds promising but is limited to MySQL unfortunately. That is the trade off for a more optimal approach I suppose. Id be curious to know if it would solve this problem.

**Comment by jprante** [comment]
The challenge is on many levels. It is not a always possible to map SQL delete straight to an equivalent operation on ES side. Only the naive case assumes that there is a table->index and row->doc equivalence. And even if so, the ES document deletes are much more expensive than in an RDBMS. Depending on the count of deletes, this can soon exercise ES for nothing. An SQL "delete from mytable" which takes milliseconds could result easily in hundred thousands operations on ES and massive segment merging for minutes. I am not sure how MongoDB river deals with this but this is definitely a challenge.

So I recommend to always add  documents, create new time-window based indices by fresh full fetches from DB, and drop old indices. Dropping indices is much faster and lightweight than massive document deletes.

**Comment by digitaldavenyc** [comment]
OK I have to ask, how can purging and reindexing the entire index be less intensive than incremental document deletes?

**Comment by jprante** [comment]
For deleting documents, the whole index has to be moved in worst case. The deleted docs are marked for later segment merging, so when they get really deleted, the merge process has to iterate through all documents. This is not very different from reindexing.
