### ISSUE TITLE
No suitable driver to sqlserver

### ISSUE THREAD

**Issue by FunkyYang** [jprante/elasticsearch-jdbc#590]
I installed the elasticsearch-jdbc and it works for mysql,but it does not work for importing data from sqlserver,I had put the sqlserver driver sqljdbc,jar in the lib directroy
How solve it ?

**Comment by jprante** [comment]
Yes, you have to put the driver in the lib directory.

**Comment by FunkyYang** [comment]
e,so what can I do to solve this problem ? :)

**Comment by alisarioglu** [comment]
Dear @FunkyYang, you have to give more information on what the problem is. If you just write it does not work, no one can guess what it is. Your configuration, log files, error messages, etc. If in the log files aren't enough information, set the level for more specific (in elastic: logging.yml and jdbc importer log4j2.xml). Open a new issues and describe in detail what is going on.

**Comment by jprante** [comment]
@FunkyYang sorry, no Microsoft support here. Ask Microsoft SQL server support for the proprietary driver jar, e.g. at https://msdn.microsoft.com/en-us/sqlserver/aa937724.aspx
This is not a problem that can be solved by JDBC importer.
