### ISSUE TITLE
Save value rom sql server as array with single value

### ISSUE THREAD

**Issue by Lars-Heesakkers** [jprante/elasticsearch-jdbc#922]
Is there any way I can save a value from sql server as an array with only one value? for example [18].

I am now retrieving the fields using the importer as follows:
`SELECT groups.RealEstatePropertyGroupId AS 'groups' FROM Elastic AS e LEFT OUTER JOIN elasticGroups AS groups ON typegroups.matchID = e.ID `

Now when this is executed and only one 'group' is available. It saves in ElasticSearch as a double (18). When multiple groups match, it is saved as an array ( [18,19] ).

Is there any way to tell the importer to always create an array, even if there is only one value?

**Comment by jprante** [comment]
See the `force_array` flag https://github.com/jprante/elasticsearch-jdbc/search?utf8=%E2%9C%93&q=force_array but it is undocumented and not usable at the moment.

Elasticsearch does not save arrays. Arrays are mapped to multi values https://www.elastic.co/guide/en/elasticsearch/guide/current/_multivalue_fields_2.html

So it does not matter how JDBC importer formats the JSON in order to get documents indexed properly.

To parse values and arrays from the JSON which is returned by Elasticsearch, use a correctly configured mapping library. I recommend Jackson http://fasterxml.github.io/jackson-databind/ with the configuration

```
ObjectMapper mapper = new ObjectMapper()
        .enable(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY);
```

It is not the job of JDBC importer to mangle JSON.

**Comment by jprante** [comment]
Sorry, the correct link for explaining multivalue fields is https://www.elastic.co/guide/en/elasticsearch/guide/2.x/complex-core-fields.html#_multivalue_fields

**Comment by Lars-Heesakkers** [comment]
My ElasticSearch code in .NET automatically maps the data to my specified object (Property) using code like : 
client.Search<Property>( ... );
In this case i wouldn't be able to use a mapping library. Am I understanding that right?

**Comment by jprante** [comment]
I don't have such problems in Java, so I think it might be a missing feature in Elasticsearch .NET client.
