### ISSUE TITLE
the script process closed when data synchronized over

### ISSUE THREAD

**Issue by hongjunsu** [jprante/elasticsearch-jdbc#951]
the script process closed when data synchronized over, 
but ,if run the script  again,es contrain two copies of the same data.
so this tow problems
1 how to clear the old data;
2 how to synchronized the new data automatic;

**Comment by jprante** [comment]
The script approach was introduced after turning JDBC river into a standalone program. Starting and stopping is  inherent to a script, but in JDBC importer, you can declare a schedule parameter so script does not stop because JDBC importer repeats forever.

You have to clear data on your own responsibility. JDBC importer is designed not to delete customer data.

There is no mechanism to detect "new data" in JDBC standard. You have to construct SQL for this purpose by yourself. It depends on the application what data is considered as "new".

**Comment by hongjunsu** [comment]
I got, must make schedule for the script.
about the 'new',can use 
How to select incremental data from a table?
